baseURL: "https://dingyu.dev/"
languageCode: "ko"
title: "Ding's Coding Forge"
theme: "PaperMod"
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true

sitemap:
  changeFreq: "daily"
  filename: "sitemap.xml"
  priority: 0.5

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home: ["HTML", "RSS", "JSON"]

services:
  googleAnalytics:
    id: G-XH8830R9KK

taxonomies:
  category: categories
  tag: tags

params:
  TocSide: "left"
  env: "production"
  title: "Ding's Things"
  description: "Go Developer Backend & DataOps"
  keywords: ["Blog", "Portfolio", "PaperMod"]
  author: "Dingyu"
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: "auto"
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: false
  hidemeta: false
  hideSummary: false
  ShowToc: true
  TocOpen: true

  giscus:
    repo: "dings-things/blog"
    repoID: "R_kgDON9IuAw"
    category: "Announcements"
    categoryID: "DIC_kwDON9IuA84CnTai"
    mapping: "og:title"
    dataStrict: "0"
    reactionsEnabled: "1"
    emitMetadata: "0"
    inputPosition: "bottom"
    theme: "preferred_color_scheme"
    lang: "en"
    loading: "lazy"

  assets:
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"

  label:
    text: "Ding's Coding Forge"
    icon: "apple-touch-icon.png"
    iconHeight: 35

  homeInfoParams:
    Title: "Problem Solver"
    Content: "Beyond a programmer — a problem solver without boundaries"

  socialIcons:
    - name: "email"
      url: "mailto:wjddn3711@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/jung-woo-lee-841950301/"
    - name: "github"
      url: "https://github.com/dings-things"

  analytics:
    google:
      SiteVerificationTag: "8XY1hI6NVxQIrN7bQbnX-9TG9HHFw5HOQmlb6vcsFdQ" 
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false
    hiddenInList: false
    hiddenInSingle: false

  editPost:
    URL: "https://github.com/dings-things/blog/tree/main/content"
    Text: "Suggest Changes"
    appendFilePath: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content", "tags"]

defaultContentLanguage: "ko"

languages:
  ko:
    languageAltTitle: 한국어
    languageName: 한국어
    weight: 1
    params:
      mainSections: ["posts"]
    menu:
      main:
        - identifier: "about"
          name: "소개"
          url: "/ko/about/"
          weight: 10
        - identifier: "categories"
          name: "카테고리"
          url: "/categories/"
          weight: 20
        - identifier: "tags"
          name: "태그"
          url: "/tags/"
          weight: 30
        - identifier: "archives"
          name: "아카이브"
          url: "/ko/archives/"
          weight: 40
        - identifier: "search"
          name: "검색"
          url: "/ko/search/"
          weight: 50

  en:
    languageAltTitle: English
    languageName: English
    weight: 2
    params:
      mainSections: ["posts"]
    menu:
      main:
        - identifier: "about"
          name: "About"
          url: "/en/about/"
          weight: 10
        - identifier: "categories"
          name: "Categories"
          url: "/categories/"
          weight: 20
        - identifier: "tags"
          name: "Tags"
          url: "/tags/"
          weight: 30
        - identifier: "archives"
          name: "Archives"
          url: "/en/archives/"
          weight: 40
        - identifier: "search"
          name: "Search"
          url: "/en/search/"
          weight: 50

markup:
  highlight:
    noClasses: false